<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="StudApprroval.aspx.cs" Inherits="onv.StudApprroval" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
    .auto-style11 {
        background-color: #FF0000;
    }
</style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div style="background-image: url('images/Approved.jpg')">

        <h3 class="auto-style300" style="background-color: #FFFFFF">STUDENT APPROOVAL</h3>
        <br />
        <strong>
        <asp:Button ID="Button4" runat="server" BackColor="#FFCC00" CssClass="auto-style10" OnClick="Button4_Click" Text="VOTE" />
        </strong>
        <asp:GridView ID="GridView1" runat="server"   BackColor="#99CCFF"  Width="940px" CssClass="auto-style12" DataKeyNames="StID" AutoGenerateDeleteButton="True" OnRowDeleting ="GridView1_RowDeleting" style="margin-left: 2px">

</asp:GridView>
             <br />
        <strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:Button ID="BtnApp" runat="server" BackColor="#FFCC00" CssClass="auto-style10" OnClick="Button2_Click" Text="APPROOVE" />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:Button ID="Button3" runat="server" BackColor="#FFCC00" CssClass="auto-style10" OnClick="Button3_Click" Text="HOME" Width="65px" />
&nbsp;&nbsp;&nbsp;&nbsp; </strong>
        <br />
        <br />
        <h4 class="auto-style11">NOTE : Once votting is over voted coloumn will fill, for next votting please vacant the voted coloumn using Vote button.</h4>
        <br />
        <br />
        <br />
        <br />

    </div>
</asp:Content>
